export const categories = [
  "Šuo",
  "Katinas",
  "Graužikas",
  "Šeškas",
  "Paukštis",
  "Triušis",
  "Roplys",
];
export const breeds = {
  Šuo: [
    "Mišrūnas",
    "Airių vilkogaudis",
    "Akita Inu",
    "Aliaskos malamutas",
    "Amerikiečių Stafordšyro terjeras",
    "Amerikiečių vandens spanielis",
    "Australijos ganymo šuo",
    "Australų aviganis",
    "Bandogas",
    "Barzdotasis kolis",
    "Basendžis",
    "Belgų aviganis",
    "Biglis",
    "Bladhaundas",
    "Bobteilas",
    "Bolonė",
    "Borderkolis",
    "Boseronas",
    "Bostono terjeras",
    "Brazilų mastifas",
    "Briaras",
    "Buldogas",
    "Bulmastifas",
    "Bulterjeras",
    "Stafordšyro bulterjeras",
    "Čiau-čiau",
    "Čihuahua",
    "Dalmatinas",
    "Dobermanas",
    "Dratharas",
    "Garbanotasis retriveris",
    "Grenlandijos šuo",
    "Griunendalis",
    "Ilgaplaukis kolis",
    "Italų mastifas",
    "Jorkšyro terjeras",
    "Kaukazo aviganis",
    "Kavalieriaus karaliaus Karolio spanielis",
    "Kurtsharas",
    "Kuvasas",
    "Lakenua",
    "Leonbergeris",
    "Levretė",
    "Lietuvių skalikas",
    "Malinua",
    "Mažasis taksas",
    "Meksikos beplaukis šuo",
    "Mopsas",
    "Naujosios Škotijos retriveris",
    "Nykštukinis pinčeris",
    "Niufaundlendas",
    "Pekinai",
    "Pinčeris",
    "Pitbulterjeras",
    "Pudelis",
    "Pulis",
    "Auksaspalvis retriveris",
    "Labradoro retriveris",
    "Ryzenčnauceris",
    "Rotveileris",
    "Saliukis",
    "Samojedų šuo",
    "Senbernaras",
    "Airių seteris",
    "Sibiro haskis",
    "Sulimovo šuo",
    "Šarpėjus",
    "Šeltis",
    "Ši Cu",
    "Taksas",
    "Terviurenas",
    "Tibeto spanielis",
    "Tosa",
    "Trumpaplaukis kolis",
    "Vakarų Škotijos baltasis terjeras",
    "Valų korgis kardiganas",
    "Vidurinės Azijos aviganis",
    "Vipetas",
    "Vokiečių aviganis",
    "Vokiečių bokseris",
    "Vokiečių dogas",
    "Vokiečių jagdterjeras",
    "Vokiečių mažasis špicas",
    "Vokiečių špicas",
    "Kita (specifikuoti aprašyme)",
  ],
  Katinas: [
    "Mišrūnas",
    "Abisinijos",
    "Amerikos Polidaktilis",
    "Amerikos šiurkščiaplaukė",
    "Amerikos trumpauodegė",
    "Amerikos trumpaplaukė",
    "Anatolijos",
    "Antipodo",
    "Arabijos Mau",
    "Australijos migla",
    "Azijos pusiau ilgaplaukė",
    "Azijos trumpaplaukė",
    "Balio",
    "Bambinas",
    "Bengalijos",
    "Birmos",
    "Bombėjaus",
    "Brazilijos trumpakailė",
    "Britų ilgakailė",
    "Britų trumpaplaukė",
    "Burmila",
    "Burmos",
    "Chausis",
    "Čantily-Tifany",
    "Devonreksas",
    "Donskio",
    "Drakonas Li",
    "Egėjo",
    "Egipto",
    "Egzotiškoji",
    "Europos trumpaplaukė",
    "Havanos rudoji",
    "Himalajų katė",
    "Japonų trumpauodegė",
    "Javos katė",
    "Jorko šokoladinė",
    "Kalifornijos žvaigždėtoji",
    "Kao Manis",
    "Kartūzų",
    "Kymro",
    "Koratas",
    "Kornreksas",
    "Kurilų trumpauodegė",
    "Lapermas",
    "Manksas",
    "Meinkūnas",
    "Minskinas",
    "Munčkinas",
    "Nebelungas",
    "Norvegų miškinė",
    "Ocelotinė",
    "Ojos Azulesas",
    "Oregono Reksas",
    "Persų ilgaplaukė",
    "Peterbaldas",
    "Piksi bobas",
    "Pusiau ilgaplaukė",
    "Ragamufinas",
    "Ragdolas",
    "Rytų dvispalvė",
    "Rytų ilgaplaukė",
    "Rytų trumpakailė",
    "Rusijos",
    "Rusų melsvoji",
    "Safario",
    "Savanos",
    "Selkirkreksas",
    "Serengečio",
    "Sfynksas",
    "Siamo",
    "Sibiro",
    "Singapūro",
    "Sokoke",
    "Somalio",
    "Spalviataškė trumpaplaukė",
    "Šito",
    "Škotų nulėpausė",
    "Šosi",
    "Tailando",
    "Toigeris",
    "Tonkino",
    "Turkų angora",
    "Turkų",
    "Ukrainos Levkojus",
    "Usūrio",
    "Vano",
    "Vokiečių reksas",
    "Kita (specifikuoti aprašyme)",
  ],

  Graužikas: [
    "Pelė",
    "Žiurkėnas",
    "Jūrų kiaulytė",
    "Žiurkė",
    "Degu",
    "Šinšila",
    "Smiltpelė",
    "Miegapelė",
    "Kita (specifikuoti aprašyme)",
  ],

  Šeškas: ["Naminis šeškas", "Kita (specifikuoti aprašyme)"],

  Paukštis: ["Papūga", "Kanarėlė", "Amadinas", "Kita (specifikuoti aprašyme)"],
  Triušis: [
    "Dekoratyvinis",
    "Nykštukinis",
    "Naujosios Zelandijos baltasis",
    "Didysis Siamo",
    "Kalifornijos",
    "Japonijos",
    "Belgų milžinas",
    "Liūtagalvis",
    "Olandijos nykštukas",
    "Havana",
    "Prancūzijos avinas",
    "Hermelinas",
    "Angora",
    "Burgundijos",
    "Vokietijos dėmėtasis",
    "Vienos pilkasis",
    "Ronas",
    "Ugninis",
    "Tiuringijos",
    "Čekijos",
    "Kiškinis",
    "Tiuringijos",
    "Kita (specifikuoti aprašyme)",
  ],
  Roplys: [
    "Vėžlys",
    "Driežas",
    "Iguana",
    "Gyvatė",
    "Kita (specifikuoti aprašyme)",
  ],
};

export const traitList = [
  "Draugiškas",
  "Dresiruotas",
  "Prieraišus",
  "Žaismingas",
  "Energingas",
  "Sutaria su kitais gyvūnais",
  "Sutaria su vaikais",
  "Gali likti vienas",
  "Gali gyventi lauke",
  "Neišrankus ėdalui",
  "Skiepytas",
  "Reikalauja daug dėmesio",
  "Lėtas",
  "Bailus",
  "Neišauklėtas",
  "Išrankus ėdalui",
  "Tinka gyventi tik namie",
  "Toleruoja keliones",
  "Negali keliauti",
  "Nesutaria su kitais gyvūnais",
  "Nesutaria su vaikais",
];

export const genders = ["Patinas", "Patelė"];

export const ages = ["Mėnesiai", "Metai"];

export const length = [
  "Ilgaplaukis",
  "Vidutinio ilgio",
  "Trumpaplaukis",
  "Plikas",
];

export const furColor = [
  "Balta",
  "Juoda",
  "Ruda",
  "Pilka",
  "Oranžinė",
  "Smėlio",
  "Mišri",
  "Raina",
  "Kita",
];
